name: first workflow
on: 
 push:
   branches:
     - 'main'
 
jobs:
  first-job:
   runs-on: ubuntu-latest
   steps: 
   - name: print greeting 
     run: | 
      echo "Hello world"
      echo "Say something"
   - name: print good bye
     run: echo "Good Bye"

